spring:
  application:
    name: Spring Boot Noop Blueprint
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DATABASE:}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:example}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 0
      initialization-fail-timeout: -1
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      continue-on-error: true

server:
  port: ${PORT:8080}
