---
components:
  - name: SpringApp
    type: service
    image: eclipse-temurin:17-jre-alpine
    port: 8080
    build:
      steps:
        - directory: /app
        - copy: [pom.xml]
          destination: ./
        - copy: src
          destination: ./src
        - run: mvn clean package
    runtime:
      command: java -jar /app/target/springboot-0.0.1-SNAPSHOT.jar -Dspring.profiles.active=${SPRING_PROFILE}
      resources:
        - PgDatabase
      variables:
        DATABASE_URL:
          $resources: PgDatabase.url
        SPRING_PROFILE: dev
        PORT: 8080
routes:
  - target:
      component: SpringApp

resources:
  - name: PgDatabase
    type: postgresql