---
components:
  - name: SpringApp
    type: service
    image:  maven:3-eclipse-temurin-17-alpine
    port: 8080
    build:
      steps:
        - directory: /app
        - copy: [pom.xml]
          destination: ./
        - copy: src
          destination: ./src
        - run: mvn package -DskipTests
        - image: eclipse-temurin:17-jdk-alpine
          stage: spring
        - copy: /app/target/*-exec.jar
          destination: /application.jar
          from: main
    runtime:
      command: java -jar /application.jar
      resources:
        - PgDatabase
      variables:
        DATABASE_URL:
          $resources: PgDatabase.url
        SPRING_PROFILE: dev
        PORT: 8080
routes:
  - target:
      component: SpringApp

resources:
  - name: PgDatabase
    type: postgresql