---
components:
  - name: SpringApp
    type: service
    image: eclipse-temurin:17-jdk-alpine
    port: 8080
    build:
      steps:
        - directory: /app
        - copy: [pom.xml mvnw]
          destination: ./
        - run: chmod u+x /app/mvnw
        - copy: .mvn
          destination: ./.mvn
        - copy: src
          destination: ./src
        - run: ./mvnw dependency:resolve
    runtime:
      command: /app/mvnw spring-boot:run -Dspring.profiles.active=${SPRING_PROFILE}
      resources:
        - PgDatabase
      variables:
        DATABASE_URL:
          $resources: PgDatabase.url
        SPRING_PROFILE: dev
        PORT: 8080
routes:
  - target:
      component: SpringApp

resources:
  - name: PgDatabase
    type: postgresql